services:
  diplomacy:
    image: ghcr.io/allan-dip/diplomacy:${TAG:-latest}
    platform: linux/amd64
    container_name: diplomacy
    pull_policy: ${PULL_POLICY:-missing}
    restart: unless-stopped
    ports:
      - 3000:80 # Web UI
      - 8433:8433 # Agent API
      - 8434-8600:8434-8600 # DAIDE server
    environment:
      # Default to only loading standard map to save minutes on server start
      MAPS_TO_LOAD: ${MAPS_TO_LOAD:-standard.map}
      SERVER_PORT: 8433
    volumes:
      - .cache/maps/:/app/maps/
